on:
  pull_request:
    branches: [ "main" ]
jobs:
  runhaskell:
    name: Run Haskell Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
#      - run: runhaskell hw_3/task_1.hs
#      - run: runhaskell hw_3/task_3.hs
#      - run: runhaskell hw_3/task_4.hs
#      - run: runhaskell hw_3/task_5.hs
#      - run: runhaskell hw_3/task_6.hs
#      - run: runhaskell hw_3/task_7.hs
#      - run: runhaskell hw_3/task_8.hs
#      - run: runhaskell hw_3/task_10.hs
      - run: runhaskell hw_4/task_3.hs
      - run: runhaskell hw_4/task_4.hs
      - run: runhaskell hw_4/task_5.hs
      - run: runhaskell hw_4/task_6.hs