on:
  pull_request:
    branches: [ "main" ]
jobs:
  runhaskell:
    name: Run Haskell Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
      - name: Compile task_1.hs and run it
        run: |
          ghc -fassertions hw_3/task_1.hs -o task1
          ./task1